# AUTOGENERATED! DO NOT EDIT! File to edit: LinearX.ipynb (unless otherwise specified).

__all__ = ['LinearX']

# Cell
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F

torch.Tensor.ndim = property(lambda x: x.dim())

# Cell
class LinearX(nn.Module):
    """
    Linear model of non-time based inputs.
    """
    def __init__(self, dims):
        super().__init__()
        if dims > 0:
            self.linear = nn.Linear(dims, 1, bias=False)

    def forward(self, x):
        if x is not None:
            return self.linear(x)
        else:
            return 0