#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Trend": "blocks.ipynb",
         "FourierModel": "blocks.ipynb",
         "Seasonal": "blocks.ipynb",
         "Squasher": "blocks.ipynb",
         "Holiday": "blocks.ipynb",
         "HolidayRange": "blocks.ipynb",
         "LinearX": "blocks.ipynb",
         "RandomWalk": "blocks.ipynb",
         "DefaultModel": "blocks.ipynb",
         "DefaultQModel": "blocks.ipynb",
         "torch.Tensor.ndim": "data.ipynb",
         "tt": "data.ipynb",
         "convert_date": "data.ipynb",
         "get_moments": "data.ipynb",
         "create_tensors": "data.ipynb",
         "TimeSeries": "data.ipynb",
         "DataFrame": "data.ipynb",
         "create_db": "data.ipynb"}

modules = ["model/blocks.py",
           "data/data.py"]

git_url = "https://github.com/fastai/profetorch/tree/master/"

def custom_doc_links(name): return None