# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"torch.Tensor.ndim": "data.ipynb",
         "FourierModel": "Fourier.ipynb",
         "Seasonal": "Fourier.ipynb",
         "Holiday": "Holidays.ipynb",
         "HolidayRange": "Holidays.ipynb",
         "LinearX": "LinearX.ipynb",
         "Squasher": "Squasher.ipynb",
         "Trend": "Trend.ipynb",
         "DefaultModel": "blocks.ipynb",
         "DefaultQModel": "blocks.ipynb",
         "L1Loss": "callbacks.ipynb",
         "PrintLoss": "callbacks.ipynb",
         "tt": "data.ipynb",
         "convert_date": "data.ipynb",
         "get_moments": "data.ipynb",
         "create_tensors": "data.ipynb",
         "TimeSeries": "data.ipynb",
         "DataFrame": "data.ipynb",
         "create_db": "data.ipynb",
         "mse": "losses.ipynb",
         "mae": "losses.ipynb",
         "q_loss": "losses.ipynb",
         "tilted_loss": "losses.ipynb",
         "weighted_loss": "losses.ipynb",
         "Model": "model.ipynb"}

modules = ["blocks/fourier.py",
           "blocks/holidays.py",
           "blocks/linearX.py",
           "blocks/squasher.py",
           "blocks/trend.py",
           "blocks/blocks.py",
           "callbacks/callbacks.py",
           "data.py",
           "losses.py",
           "model.py"]

doc_url = "https://sachinruk.github.io/ProFeTorch/"

git_url = "https://github.com/sachinruk/profetorch/tree/master/"

def custom_doc_links(name): return None
